### PR TITLE
Implemented the 'creategameobject' client command handler

### PR DESCRIPTION
**Pull request by natrist**
Usage: cgo <objectID>

---
This change is [Reviewable](https://reviewable.io/reviews/mangostwo/server/178)

### CODE REVIEW

**Comment by natrist** [comment]
I am aware that line ending is all messed up and will follow up with a fix. In the mean time, can anyone please explain the display ID check? I don't see how it is necessary.

**Comment by billy1arm** [comment]
> I am aware that line ending is all messed up and will follow up with a fix. In the mean time, can anyone please explain the display ID check? I don't see how it is necessary.

If I remember correctly, the wotlk client will crash or act unpredictably if the displayId is invalid

**Review by billy1arm — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mangostwo/server/178)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by natrist — COMMENTED** [review]
Everything looks good to me. Waiting for approval...

**Comment by Elmsroth** [comment]
You meant client opcode ? @natrist 
I thought it was  a GM command but no it's an OpCode handling .
Nice job :)

**Comment by Meltie2013** [comment]
@Elmsroth Most commands use packets when adding something to the world. (e.g. Game Objects, Creatures and Items) to name a few.

**Comment by natrist** [comment]
@Elmsroth It's for the GM client I'm working on. I'll release it shortly.

**Comment by Elmsroth** [comment]
Okay :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request merged**
