### PR TITLE
Fixed a bug where the Dungeon Finder would cause a crash on queuing

### PR DESCRIPTION
**Pull request by natrist**
Initially reported by JetFox#2538 on Discord.

---
This change is [Reviewable](https://reviewable.io/reviews/mangostwo/server/173)

### CODE REVIEW

**Comment by Elmsroth** [comment]
Noce done @natrist  !

**Comment by billy1arm** [comment]
@natrist Thank you

**Comment by MadMaxMangos** [comment]
Does this fix the original issue as reported in 2018? https://www.getmangos.eu/bug-tracker/mangos-two/dungeon-raid-finder-r1515/

**Comment by natrist** [comment]
> Does this fix the original issue as reported in 2018? https://www.getmangos.eu/bug-tracker/mangos-two/dungeon-raid-finder-r1515/

It fixes the crash but the myriad of other issues revolving around the Dungeon Finder are still present. I will work on refactoring the entire system this week.

**Pull request merged**
